(load "p41_1.3.2_lambda.scm")
(define (simpson-own f a b n)
    (define h (/ (- b a) n))
    (define (next x) (+ x (* 2.0 h)))
    (define (inter-f a) (+ (* 2.0 (f a))
                           (* 4.0 (f (+ a h)))))
    (* (/ h 3)
       (+ (f a) (f b) 
            (* 4.0 (+ a h)) 
            (sum inter-f (next a) next (- b (* 2 h)))))
    )

(define (simpson f a b n) 
    (define h (/ (- b a) n))
    (define (factor k)
        (cond  ((or (= k 0) (= k n)) 1.0)
               ((odd? k) 4.0)
               (else 2.0)))
    (define (term k) (* (factor k) (f (+ a (* k h)))))
    (* (/ h 3) (sum term 0 1+ n))
    )

